---
- name: "Load users"
  include_vars:
    dir: "{{ github_users_dir }}"
    files_matching: >-
      {% if github_users__include is defined %}^{{ github_users__include }}\.yml{% endif %}
    ignore_unknown_extensions: yes
    name: users

- name: "Manage organization members"
  when:
    - github_members__state is string
    - github_members__state | length > 0
  include_tasks: org-members.yml

- name: "Manage teams"
  when:
    - github_teams__state is string
    - github_teams__state | length > 0
  include_tasks: teams.yml

- name: "Manage repositories"
  when:
    - github_repos__state is string
    - github_repos__state | length > 0
  include_tasks: repos.yml
