---
- name: load users
  include_vars:
    ignore_unknown_extensions: yes
    dir: "{{ github_users_dir }}"
    name: users
    files_matching: >-
      {% if github_users__include is defined %}{{ github_users__include }}.yml{% endif %}

- name: manage organization members
  include: org-members.yml
  when:
    - github_members__state is string
    - github_members__state | length > 0

- name: manage teams
  include: teams.yml
  when:
    - github_teams__state is string
    - github_teams__state | length > 0

- name: manage repos
  include: repos.yml
  when:
    - github_repos__state is string
    - github_repos__state | length > 0
