---
- name: "Get admins of the {{ github_org }} organization"
  include_tasks: org-members-role.yml
  vars:
    role: admin
    mmbrs_var: org_admin

- name: "Get ordinary members of the {{ github_org }} organization"
  include_tasks: org-members-role.yml
  vars:
    role: member
    mmbrs_var: org_member

- name: "Dump all members of the {{ github_org }} organization"
  copy:
    content: |
      {{ github_org }}:
        name: {{ orgs[github_org].name }}
      {% if org_admin | length > 0 %}
        admin:
      {{ org_admin | sort | to_nice_yaml | indent(4, true) }}
      {%- endif %}
      {% if org_member | length > 0 %}
        member:
      {{ org_member | sort | to_nice_yaml | indent(4, true) }}
      {%- endif %}
    dest: "{{ role_path }}/{{ github_vars_dir }}/orgs/{{ github_org }}.yml"
