---
- name: "Remove {{ mmbr }} from the {{ github_org }} organization"
  when: users[mmbr] is defined
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    method: DELETE
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/memberships/{{ users[mmbr].github }}'
  register: response
