---
- name: "Get admins of the {{ github_org }} organization"
  include_tasks: org-members-role.yml
  vars:
    role: admin
    mmbrs_var: org_admin

- name: "Get ordinary members of the {{ github_org }} organization"
  include_tasks: org-members-role.yml
  vars:
    role: member
    mmbrs_var: org_member

- name: "Update all the supplied {{ orgs[github_org].admin | length }} admins of the {{ github_org }} organization"
  loop: "{{ orgs[github_org].admin }}"
  loop_control:
    loop_var: mmbr
  include_tasks: org-member-present.yml
  vars:
    role: admin

- name: "Update all the supplied {{ orgs[github_org].member | length }} members of the {{ github_org }} organization"
  loop: "{{ orgs[github_org].member }}"
  loop_control:
    loop_var: mmbr
  include_tasks: org-member-present.yml
  vars:
    role: member

- name: "Remove {{ unknown | length }} unspecified members from the {{ github_org }} organization"
  loop: "{{ unknown }}"
  loop_control:
    loop_var: mmbr
  include_tasks: org-member-absent.yml
  vars:
    unknown: >-
      {{    org_admin  | difference(orgs[github_org].admin  | default([]))  |
      union(org_member | difference(orgs[github_org].member | default([]))) }}
