---
- name: "Update {{ mmbr }}'s {{ role }} role at the {{ github_org }} organization"
  when:
    - users[mmbr] is defined
    - users[mmbr].status.active | bool
  uri:
    body: "{{ body | to_json }}"
    body_format: json
    force_basic_auth: yes
    method: PUT
    password: "{{ github_token }}"
    url: '{{ github_api }}/orgs/{{ github_org }}/memberships/{{ users[mmbr].github }}'
    user: "{{ github_user }}"
  vars:
    body:
      role: "{{ role }}"
  register: response

- name: "Remove inactive {{ mmbr }} from the {{ github_org }} organization"
  when:
    - users[mmbr] is defined
    - not users[mmbr].status.active | bool
  include: org-member-absent.yml
  register: response
