---
- name: Initialize members list with an empty value
  set_fact:
    mmbrs: []

- name: "Get all {{ github_org }} organization's members"
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    url: "{{ github_api }}/orgs/{{ github_org }}/members\
      ?per_page={{ github_per_page }}\
      &page={{ page }}\
      &role={{ role }}"
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
  register: response
  # Do the next loop iteration with the very first page (when the response does not exist yet) or if
  # the last response returned anything.  If the last response was empty, than it's time to finish the loop.
  when: page == 1 or response.json | length > 0

- name: >-
    Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }}
    {{ github_org }} org's {{ role }}s
  loop: "{{ response | json_query('results[*].json[*][login]') | flatten }}"
  loop_control:
    loop_var: member
  set_fact:
    mmbrs: "{{ mmbrs + username }}"
  vars:
    query: "[? value.github == '{{ member }}'].key"
    username: "{{ lookup('dict', users) | json_query(query) }}" # a list of zero or one element
