---
- name: "Get all the {{ repo_name }} repository's teams"
  include_tasks: repo-teams.yml

- name: "Get all {{ repo.name }}'s direct collaborators"
  include_tasks: repo-collaborators.yml
  vars:
    affiliation: direct
    cllbrtrs_var: cllbrtrs_direct
    repo_name: "{{ repo.name }}"

- name: "Get all {{ repo.name }}'s outside collaborators"
  include_tasks: repo-collaborators.yml
  vars:
    affiliation: outside
    cllbrtrs_var: cllbrtrs_outside
    repo_name: "{{ repo.name }}"

- name: "Dump the {{ repo.name }} repo"
  copy:
    content: |
      {{ repo.name }}:
      {% if repo.archived != github_repo_archived %}
        archived: {{ not github_repo_archived }}
      {% endif %}
      {% if repo.default_branch != 'master' %}
        default_branch: {{ repo.default_branch }}
      {% endif %}
      {% if repo.description is defined and repo.description != '' %}
        description: >-
          {{ repo.description }}
      {% endif %}
      {% if repo.has_issues != github_repo_has_issues %}
        has_issues: {{ not github_repo_has_issues }}
      {% endif %}
      {% if repo.has_projects != github_repo_has_projects %}
        has_projects: {{ not github_repo_has_projects }}
      {% endif %}
      {% if repo.has_wiki != github_repo_has_wiki %}
        has_wiki: {{ not github_repo_has_wiki }}
      {% endif %}
      {% if repo.homepage is defined and repo.homepage != '' %}
        homepage: {{ repo.homepage }}
      {% endif %}
      {% if repo.language is defined and repo.language != '' %}
        language: {{ repo.language }}
      {% endif %}
      {% if repo.private != github_repo_private %}
        private: {{ not github_repo_private }}
      {% endif %}
      {% if (repo_admin | length) + (repo_push | length) + (repo_pull | length) > 0 %}
        teams:
      {% if repo_admin | length > 0 %}
          admin:
      {{ repo_admin | sort | to_nice_yaml | indent(6, true) }}
      {%- endif %}
      {% if repo_push | length > 0 %}
          push:
      {{ repo_push | sort | to_nice_yaml | indent(6, true) }}
      {%- endif %}
      {% if repo_pull | length > 0 %}
          pull:
      {{ repo_pull | sort | to_nice_yaml | indent(6, true) }}
      {%- endif %}
      {%- endif %}
      {% if (cllbrtrs_direct | length) + (cllbrtrs_outside | length) > 0 %}
        collaborators:
      {% if cllbrtrs_direct | length > 0 %}
          direct:
      {{ cllbrtrs_direct | sort | to_nice_yaml | indent(6, true) }}
      {%- endif %}
      {% if cllbrtrs_outside | length > 0 %}
          outside:
      {{ cllbrtrs_outside | sort | to_nice_yaml | indent(6, true) }}
      {%- endif %}
      {%- endif %}
    dest: "{{ role_path }}/{{ github_vars_dir }}/repos/{{ repo.name }}.yml"
