---
- name: "Expell the {{ team }} team from the {{ repo.key }} repository"
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    method: DELETE
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
  register: response
