---
- name: "Grant {{ perm.key }} permission for the {{ team }} team on the {{ repo.key }} repo"
  when: perm.key != 'absent'
  uri:
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
    method: PUT
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
    body_format: json
    body: "{ 'permission': '{{ perm.key }}' }"
    status_code: 204
  register: response

- name: "Revoke {{ perm.key }} permission for the {{ team }} team on the {{ repo.key }} repo"
  when: perm.key == 'absent'
  uri:
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
    method: DELETE
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
    status_code: 204
  register: response
