---
- name: "Load repositories"
  include_vars:
    dir: "{{ role_path }}/{{ github_vars_dir }}/repos"
    files_matching: >-
      {% if github_repos__include is defined %}^{{ github_repos__include }}\.yml{% endif %}
    ignore_unknown_extensions: yes
    name: repos

- name: "Update all the supplied {{ repos | length }} repositories"
  when: github_repos__state == 'present'
  loop: "{{ query('dict', repos) }}"
  loop_control:
    loop_var: repo
  include_tasks: repo-present.yml

- name: "Dump all existing repositories into {{ role_path }}/{{ github_vars_dir }}/repos directory"
  when: github_repos__state == 'dump'
  include_tasks: repos-dump.yml
