---
- name: "Dump all Github repos"
  when: page == 1 or response.json | length > 0
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    force_basic_auth: yes
    password: "{{ github_token }}"
    url: '{{ github_api }}/orgs/{{ github_org }}/repos?per_page={{ github_per_page }}&page={{ page }}'
    user: "{{ github_user }}"
  register: response

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} repos"
  when: github_repos__include is not defined or repo.name == github_repos__include
  loop: "{{ response | json_query('results[*].json[*]') | flatten }}"
  loop_control:
    loop_var: repo
  include_tasks: repo-dump.yml
  vars:
    repo_name: "{{ repo.name }}"
