---
- name: "Update {{ clbr }}'s collaboration {{ permission }} permission at {{ repo.key }} repo"
  uri:
    body: "{{ body | to_json }}"
    body_format: json
    force_basic_auth: yes
    method: PUT
    password: "{{ github_token }}"
    status_code: 204
    url: "{{ github_api }}/repos/{{ github_org }}/{{ repo.key }}/collaborators/{{ clbr }}"
    user: "{{ github_user }}"
  vars:
    body:
      permission: "{{ permission }}"
  register: response
