---
- name: "Remove {{ clbr }}'s collaborator from the {{ repo.key }} repository"
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    method: DELETE
    status_code: 204
    url: "{{ github_api }}/repos/{{ github_org }}/{{ repo.key }}/collaborators/{{ clbr }}"
  register: response
