---
- name: "Check whether {{ repo.key }} repository exists"
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    status_code:
      - 200
      - 404
    url: '{{ github_api }}/repos/{{ github_org }}/{{ repo.key }}'
  register: response

- name: "Create new {{ repo.key }} repository"
  when: response.status == 404
  uri:
    body: "{{ repo.value | combine({ 'name': repo.key }) | to_json }}"
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
    method: POST
    status_code: 201
    url: '{{ github_api }}/orgs/{{ github_org }}/repos'

- name: "Update existing {{ repo.key }} repository"
  when: response.status == 200
  uri:
    body: "{{ repo.value | combine({ 'name': repo.key }) | to_json }}"
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
    method: PATCH
    url: '{{ github_api }}/repos/{{ github_org }}/{{ repo.key }}'
  # just continue in case of an archived repo
  ignore_errors: "{{ repo.value.archived | default(false) | bool }}"

- name: "Update {{ repo.key }} repository"
  when: not (repo.value.archived | default(false))
  include: repo-permissions.yml
