---
- name: "Grant {{ perm.key }} permission for the {{ team }} team on the {{ repo.key }} repo"
  when: perm.key != 'absent'
  uri:
    body: "{{ body | to_json }}"
    body_format: json
    force_basic_auth: yes
    method: PUT
    password: "{{ github_token }}"
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
    user: "{{ github_user }}"
  vars:
    body:
      permission: "{{ perm.key }}"
  register: response

- name: "Revoke {{ perm.key }} permission for the {{ team }} team on the {{ repo.key }} repo"
  when: perm.key == 'absent'
  uri:
    force_basic_auth: yes
    method: DELETE
    password: "{{ github_token }}"
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
    user: "{{ github_user }}"
  register: response
