---
- name: "Grant {{ perm.key }} permission for the {{ team }} team on the {{ repo.key }} repo"
  uri:
    body: "{{ body | to_json }}"
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
    method: PUT
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team }}/repos/{{ github_org }}/{{ repo.key }}'
  vars:
    body:
      permission: "{{ permission }}"
  register: response
