---
- name: dump all Github teams
  # Include here as many items as you expect to be pages of teams.
  # At the time of this writing there are 116 teams.
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    url: '{{ github_api }}/orgs/{{ github_org }}/teams?per_page={{ github_per_page }}&page={{ page }}'
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
  register: response
  # Do the next loop iteration with the very first page (when the response does not exist yet) or if
  # the last response returned anything.  If the last response was empty, than it's time to finish the loop.
  when: page == 1 or response.json | length > 0

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} teams"
  loop: "{{ response | json_query('results[*].json[*]') | flatten }}"
  loop_control:
    loop_var: team
  include: team-dump.yml
