---
- name: "Update {{ mmbr }}'s {{ role }} membership in {{ team.key }}"
  when:
    - role != 'absent'
    - users[mmbr].github is defined
  uri:
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team.key }}/memberships/{{ users[mmbr].github }}'
    method: PUT
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
    body_format: json
    body: "{ 'role': '{{ role }}' }"
  register: response

- name: "Remove {{ mmbr }} from {{ team.key }}"
  when:
    - role == 'absent'
    - users[mmbr].github is defined
  uri:
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team.key }}/memberships/{{ users[mmbr].github }}'
    method: DELETE
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: yes
    status_code: 204
  register: response
