---
## Github does not show role of a member in the list of team members.
## Therefore we have to retrieve all members separately by their roles.
- name: "Get maintainers of {{ team.slug }} team"
  include_tasks: team-members.yml
  vars:
    role: maintainer
    mmbrs_var: team_maintainer
    team_slug: team.slug

- name: "Get ordinary members of {{ team.slug }} team"
  include_tasks: team-members.yml
  vars:
    role: member
    mmbrs_var: team_member
    team_slug: team.slug

- name: "Dump the {{ team.slug }} team"
  copy:
    ## Github has complex default for team's privacy, so we don't have a default value.
    content: |
      {{ team.slug }}:
      {% if team.name is defined and team.name != team.slug %}
        name: {{ team.name }}
      {% endif %}
      {% if team.description is defined and team.description != '' %}
        description: >-
          {{ team.description }}
      {% endif %}
        privacy: {{ team.privacy }}
      {% if team.parent is mapping %}
        parent: {{ team.parent.slug }}
      {% endif -%}
      {% if team_maintainer | length > 0 %}
        maintainer:
      {{ team_maintainer | sort | to_nice_yaml | indent(4, true) }}
      {%- endif %}
      {% if team_member | length > 0 %}
        member:
      {{ team_member | sort | to_nice_yaml | indent(4, true) }}
      {%- endif %}
    dest: "{{ role_path }}/{{ github_vars_dir }}/teams/{{ team.slug }}.yml"
