---
- name: "Remove {{ mmbr }} from {{ team.key }}."
  when: users[mmbr].github is defined
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    method: DELETE
    status_code: 204
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team.key }}/memberships/{{ users[mmbr].github }}'
  register: response
