---
- name: "Update {{ mmbr }}'s {{ role }} membership in {{ team.key }}"
  when: users[mmbr].github is defined
  uri:
    body: "{{ body | to_json }}"
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
    method: PUT
    url: '{{ github_api }}/orgs/{{ github_org }}/teams/{{ team.key }}/memberships/{{ users[mmbr].github }}'
  vars:
    body:
      role: "{{ role }}"
  register: response
