---
- name: "Dump all teams"
  when: page == 1 or response.json | length > 0
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    force_basic_auth: yes
    password: "{{ github_token }}"
    url: '{{ github_api }}/orgs/{{ github_org }}/teams?per_page={{ github_per_page }}&page={{ page }}'
    user: "{{ github_user }}"
  register: response

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} teams"
  when: github_teams__include is not defined or team.name == github_teams__include
  loop: "{{ response | json_query('results[*].json[*]') | flatten }}"
  loop_control:
    loop_var: team
  include_tasks: team-dump.yml
