---
- name: load teams
  include_vars:
    dir: "{{ github_vars_dir }}/teams"
    name: teams
    files_matching: >-
      {% if github_teams__include is defined %}^{{ github_teams__include }}\.yml{% endif %}

- name: "Update all the supplied {{ teams | length }} teams"
  loop: "{{ query('dict', teams) }}"
  loop_control:
    loop_var: team
  include: team-present.yml
  when: github_teams__state == 'present'

- name: "Dump all existing teams into {{ github_vars_dir }}/teams directory"
  include: teams-dump.yml
  when: github_teams__state == 'dump'
